export {default as Blog} from './blog/Blog'
export {default as Features} from './features/Features'
export {default as Footer} from './footer/Footer'
export {default as Header} from './header/Header'
export {default as Possibility} from './possibility/Possibility'
export {default as AboutUs} from './aboutUs/aboutUs'
export {default as Pricing} from '../pages/pricing'    